// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriApp.Data;

#nullable disable

namespace NutriApi.Migrations
{
    [DbContext(typeof(NutriAppDbContext))]
    [Migration("20260923044221_RefactorEquivalenciasAutomaticas")]
    partial class RefactorEquivalenciasAutomaticas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Calorias")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CantidadBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Carbohidratos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CategoriaAlimentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Grasas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Proteinas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("UnidadBase")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaAlimentoId");

                    b.HasIndex("NutricionistaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.CategoriaAlimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId", "Nombre")
                        .IsUnique();

                    b.ToTable("CategoriasAlimentos");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.EquivalenciaAlimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoEquivalenciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("GrupoEquivalenciaId", "AlimentoId")
                        .IsUnique();

                    b.ToTable("EquivalenciasAlimentos");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.GrupoEquivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Criterio")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId");

                    b.ToTable("GruposEquivalencias");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.AlternativaItemComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoEquivalenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemOpcionComidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("GrupoEquivalenciaId");

                    b.HasIndex("ItemOpcionComidaId", "AlimentoId")
                        .IsUnique();

                    b.ToTable("AlternativasItemsComidas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Comida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietaId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Dietas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.HidratacionDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MililitrosDiarios")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("VasosDiarios")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietaId")
                        .IsUnique();

                    b.ToTable("HidratacionesDietas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.ItemOpcionComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text");

                    b.Property<int>("OpcionSeccionComidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("OpcionSeccionComidaId");

                    b.ToTable("ItemsOpcionesComidas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.ItemSuplementacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text");

                    b.Property<string>("Momento")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("SuplementacionDietaId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SuplementacionDietaId");

                    b.ToTable("ItemsSuplementacion");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.OpcionSeccionComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionComidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeccionComidaId");

                    b.ToTable("OpcionesSeccionesComidas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SeccionComida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComidaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComidaId");

                    b.ToTable("SeccionesComidas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SuplementacionDieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaId")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DietaId")
                        .IsUnique();

                    b.ToTable("SuplementacionesDietas");
                });

            modelBuilder.Entity("NutriApp.Models.Notificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<string>("RecursoTipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaCreacion");

                    b.HasIndex("UsuarioId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("NutriApp.Models.Pacientes.NotaPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("integer");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("NotasPacientes");
                });

            modelBuilder.Entity("NutriApp.Models.Pacientes.PerfilPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadDescripcion")
                        .HasColumnType("text");

                    b.Property<decimal?>("Altura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("ObjetivoNutricional")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoInicial")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("TipoActividad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("PerfilesPacientes");
                });

            modelBuilder.Entity("NutriApp.Models.Pagos.PagoPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text");

                    b.Property<decimal?>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ProximoVencimiento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "ProximoVencimiento");

                    b.ToTable("PagosPacientes");
                });

            modelBuilder.Entity("NutriApp.Models.Seguimiento.SeguimientoSemanalPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adherencia")
                        .HasColumnType("integer");

                    b.Property<int>("CumplimientoHidratacion")
                        .HasColumnType("integer");

                    b.Property<int>("Descanso")
                        .HasColumnType("integer");

                    b.Property<string>("DetalleDigestiones")
                        .HasColumnType("text");

                    b.Property<string>("DetalleMolestiaFisica")
                        .HasColumnType("text");

                    b.Property<int>("Digestiones")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaFinSemana")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicioSemana")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRevisionNutricionista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoActual")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("RegularidadIntestinal")
                        .HasColumnType("integer");

                    b.Property<int>("RendimientoEntrenamientos")
                        .HasColumnType("integer");

                    b.Property<string>("RevisionNutricionista")
                        .HasColumnType("text");

                    b.Property<int>("SatisfaccionComunicacion")
                        .HasColumnType("integer");

                    b.Property<bool>("TuvoMolestiaFisica")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "FechaInicioSemana")
                        .IsUnique();

                    b.ToTable("SeguimientosSemanalesPacientes");
                });

            modelBuilder.Entity("RegistroDiarioPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaderaCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("CinturaCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("CuelloCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool?>("CumplioPlan")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GemeloCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "Fecha")
                        .IsUnique();

                    b.ToTable("RegistrosDiariosPacientes");
                });

            modelBuilder.Entity("Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkReunion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Lugar")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "FechaHora");

                    b.HasIndex("PacienteId", "FechaHora");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("UsuarioAplicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NutriApp.Models.Usuarios.Paciente", b =>
                {
                    b.HasBaseType("UsuarioAplicacion");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("NutricionistaId")
                        .HasColumnType("integer");

                    b.HasIndex("NutricionistaId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("Nutricionista", b =>
                {
                    b.HasBaseType("UsuarioAplicacion");

                    b.Property<string>("Matricula")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Nutricionista");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.Alimento", b =>
                {
                    b.HasOne("NutriApp.Models.Alimentos.CategoriaAlimento", "Categoria")
                        .WithMany("Alimentos")
                        .HasForeignKey("CategoriaAlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nutricionista", "Nutricionista")
                        .WithMany("Alimentos")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.CategoriaAlimento", b =>
                {
                    b.HasOne("Nutricionista", "Nutricionista")
                        .WithMany("CategoriasAlimentos")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.EquivalenciaAlimento", b =>
                {
                    b.HasOne("NutriApp.Models.Alimentos.Alimento", "Alimento")
                        .WithMany("Equivalencias")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriApp.Models.Alimentos.GrupoEquivalencia", "GrupoEquivalencia")
                        .WithMany("Equivalencias")
                        .HasForeignKey("GrupoEquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("GrupoEquivalencia");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.GrupoEquivalencia", b =>
                {
                    b.HasOne("Nutricionista", "Nutricionista")
                        .WithMany("GruposEquivalencias")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.AlternativaItemComida", b =>
                {
                    b.HasOne("NutriApp.Models.Alimentos.Alimento", "Alimento")
                        .WithMany("Alternativas")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriApp.Models.Alimentos.GrupoEquivalencia", "GrupoEquivalencia")
                        .WithMany()
                        .HasForeignKey("GrupoEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriApp.Models.Dietas.ItemOpcionComida", "ItemOpcionComida")
                        .WithMany("Alternativas")
                        .HasForeignKey("ItemOpcionComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("GrupoEquivalencia");

                    b.Navigation("ItemOpcionComida");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Comida", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.Dieta", "Dieta")
                        .WithMany("Comidas")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Dieta", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany("Dietas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.HidratacionDieta", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.Dieta", "Dieta")
                        .WithOne("Hidratacion")
                        .HasForeignKey("NutriApp.Models.Dietas.HidratacionDieta", "DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.ItemOpcionComida", b =>
                {
                    b.HasOne("NutriApp.Models.Alimentos.Alimento", "Alimento")
                        .WithMany("ItemsComida")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriApp.Models.Dietas.OpcionSeccionComida", "OpcionSeccionComida")
                        .WithMany("Items")
                        .HasForeignKey("OpcionSeccionComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("OpcionSeccionComida");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.ItemSuplementacion", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.SuplementacionDieta", "SuplementacionDieta")
                        .WithMany("Items")
                        .HasForeignKey("SuplementacionDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuplementacionDieta");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.OpcionSeccionComida", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.SeccionComida", "SeccionComida")
                        .WithMany("Opciones")
                        .HasForeignKey("SeccionComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeccionComida");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SeccionComida", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.Comida", "Comida")
                        .WithMany("Secciones")
                        .HasForeignKey("ComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comida");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SuplementacionDieta", b =>
                {
                    b.HasOne("NutriApp.Models.Dietas.Dieta", "Dieta")
                        .WithOne("Suplementacion")
                        .HasForeignKey("NutriApp.Models.Dietas.SuplementacionDieta", "DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("NutriApp.Models.Notificaciones.Notificacion", b =>
                {
                    b.HasOne("UsuarioAplicacion", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NutriApp.Models.Pacientes.NotaPaciente", b =>
                {
                    b.HasOne("Nutricionista", "Nutricionista")
                        .WithMany("NotasPacientes")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany("Notas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nutricionista");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriApp.Models.Pacientes.PerfilPaciente", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithOne("Perfil")
                        .HasForeignKey("NutriApp.Models.Pacientes.PerfilPaciente", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriApp.Models.Pagos.PagoPaciente", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany("Pagos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriApp.Models.Seguimiento.SeguimientoSemanalPaciente", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany("SeguimientosSemanales")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("RegistroDiarioPaciente", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany("RegistrosDiarios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Turno", b =>
                {
                    b.HasOne("NutriApp.Models.Usuarios.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("NutriApp.Models.Usuarios.Paciente", b =>
                {
                    b.HasOne("Nutricionista", "Nutricionista")
                        .WithMany("Pacientes")
                        .HasForeignKey("NutricionistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.Alimento", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Equivalencias");

                    b.Navigation("ItemsComida");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.CategoriaAlimento", b =>
                {
                    b.Navigation("Alimentos");
                });

            modelBuilder.Entity("NutriApp.Models.Alimentos.GrupoEquivalencia", b =>
                {
                    b.Navigation("Equivalencias");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Comida", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.Dieta", b =>
                {
                    b.Navigation("Comidas");

                    b.Navigation("Hidratacion");

                    b.Navigation("Suplementacion");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.ItemOpcionComida", b =>
                {
                    b.Navigation("Alternativas");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.OpcionSeccionComida", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SeccionComida", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("NutriApp.Models.Dietas.SuplementacionDieta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NutriApp.Models.Usuarios.Paciente", b =>
                {
                    b.Navigation("Dietas");

                    b.Navigation("Notas");

                    b.Navigation("Pagos");

                    b.Navigation("Perfil");

                    b.Navigation("RegistrosDiarios");

                    b.Navigation("SeguimientosSemanales");
                });

            modelBuilder.Entity("Nutricionista", b =>
                {
                    b.Navigation("Alimentos");

                    b.Navigation("CategoriasAlimentos");

                    b.Navigation("GruposEquivalencias");

                    b.Navigation("NotasPacientes");

                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
